In [18]:
import tensorflow as tf
import pandas as pd
import tensorflow_datasets as tfds
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [21]:
def retrieve_iris_data():
    iris_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
    cache_dir = '.'
    cache_subdir = 'data'
    iris_file = tf.keras.utils.get_file('iris_data', iris_url,
                                        cache_dir=cache_dir, cache_subdir=cache_subdir)
    return iris_file

iris_collumns = ['sepal_length',  'sepal_with', 'peta_length', 'peta_with', 'species']
label_map = {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}
def parse_iris_data(iris_filepath):
    iris_df = pd.read_csv(iris_filepath, names=iris_collumns)
    iris_df['species'].replace(label_map, inplace=True)

    return iris_df

def convert_iris_to_dataset(iris_dataframe):
    features = iris_dataframe[iris_collumns[:4]]
    labels = iris_dataframe[iris_collumns[-1]]
    iris_dataset = tf.data.Dataset.from_tensor_slices((features, labels))
    return iris_dataset


In [22]:
iris_filepath = retrieve_iris_data()
iris_data = parse_iris_data(iris_filepath)
iris_ds = convert_iris_to_dataset(iris_data)

In [23]:
for d, l in iris_ds.take(5):
    print(d,l)

tf.Tensor([5.1 3.5 1.4 0.2], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([4.9 3.  1.4 0.2], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([4.7 3.2 1.3 0.2], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([4.6 3.1 1.5 0.2], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([5.  3.6 1.4 0.2], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)
